name: backend
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@c3
        with:
          python-version: "3.6"
      -run: |
          cd back
          sudo pip install awscli
          sudo aws ecr get-login-password --region ap-east-1 | sudo docker login --username AWS --password-stdin 737976497055.dkr.ecr.ap-east-1.amazonaws.com
          sudo docker build -t ty-project
          sudo docker tag ty-project:latest 737976497055.dkr.ecr.ap-east-1.amazonaws.com/ty-project:latest
          sudo docker push 737976497055.dkr.ecr.ap-east-1.amazonaws.com/ty-project:latest
      - uses: fifsky/ssh-action@master
        with:
        command: |
          sudo docker pull 737976497055.dkr.ecr.ap-east-1.amazonaws.com/ty-project:latest
          sudo docker-compose down
          sudo docket-compose up -d
        host: 172.31.8.94
        user: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}
      